Allow smtp connection without SSL
jellyfin/jellyfin-plugin-webhook pull request #258
Opened 2024-06-29 23:58 UTC by RyanMelena

Per MailKit documentation:

> useSsl argument only controls whether or not the client makes an SSL-wrapped connection. In other words, even if the useSsl parameter is false, SSL/TLS may still be used if the mail server supports the STARTTLS extension.  To disable all use of SSL/TLS, use the ConnectAsync(string,int,MailKit.Security.SecureSocketOptions,System.Threading.CancellationToken overload with a value of SecureSocketOptions.None instead.

fix #120, fix #226

2024-06-30 01:03 UTC, crobibero approved these changes

2024-06-30 20:08 UTC, oddstr13 requested changes
This does not look like a good solution, as it, per the documentation, will carry on without encryption if it is unable to connect with either starttls or ssl.
This would allow MITM by manipulating the traffic a little bit.

None of the available options are a good fit for a boolean "use encryption?".
It would be better to expose all/several options in a dropdown box.
I'd suggest;
- No encryption
- Attempt encryption (auto, fall back to none)
- SSL (enforce SSL, otherwise fail)
- StartTLS (enforce StartTLS, otherwise fail)

https://mimekit.net/docs/html/T_MailKit_Security_SecureSocketOptions.htm

2024-07-01 00:59 UTC, RyanMelena commented
@oddstr13 Do you think that level of complexity is necessary?  I'd guess most cases where encryption isn't used would be people self-hosting an SMTP relay as virtually all public SMTP servers now require TLS.  Most hardware devices that I've seen that allow SMTP notifications just present a checkbox for "Use SSL / TLS".

2024-07-01 14:39 UTC, crobibero commented
I think for proper flexibility the full list should be implemented

2024-07-01 15:25 UTC, RyanMelena commented
To be frank, I don't see the advantage.  Thought this might be an easy win that would address a couple open issues but I don't use the SMTP feature myself and am not interested in performing a larger refactor.  Please feel free to close out the PR.

2024-07-01 20:23 UTC, oddstr13 commented
I think it is very important to actually use encryption when you say you will.

The proper fix for the mentioned issue, is to either configure SSL certificates properly with domain names, and use that domain name when connecting, or disable encryption on the server.

Us saying "whatever, we'll do without" if encryption fails, when the user has explicitly said that encryption is desired, is _not ok._

Ideally, we'd have an auto option that doesn't fall back to no encryption.

2024-07-01 21:57 UTC, RyanMelena commented
I'm not following the argument here.  As I understand it, the existing code is currently using "Attempt encryption" option in all circumstances.

What seemed to be missing currently, according the the referenced issues, is a way to force the SMTP connection to use an unencrypted connection when your SMTP server (again, most likely a local relay) isn't configured for encryption.

If the argument is that the current code is insecure because it may fall back to an unencrypted connection then I would think that is a separate issue from this PR which just adds the ability to force an unencrypted connection.

https://mimekit.net/docs/html/M_MailKit_MailService_ConnectAsync_3.htm

> 
> The useSsl argument only controls whether or not the client makes an SSL-wrapped connection. In other words, even if the useSsl parameter is false, SSL/TLS may still be used if the mail server supports the STARTTLS extension.
> 
> To disable all use of SSL/TLS, use the [ConnectAsync(String, Int32, SecureSocketOptions, CancellationToken)](https://mimekit.net/docs/html/M_MailKit_MailService_ConnectAsync_2.htm) overload with a value of [SecureSocketOptions.None](https://mimekit.net/docs/html/T_MailKit_Security_SecureSocketOptions.htm) instead.

2024-07-01 22:04 UTC, RyanMelena commented
I may have been mistaken about the existing behavior.  Looking at the implementation of the [existing call in MailKit](https://github.com/jstedfast/MailKit/blob/c39a209f6f196447e069306a13821f3b10b5ab7b/MailKit/MailService.cs#L1130C17-L1131C1) it appears that the `useSsl` boolean just switches between `SecureSocketOptions.SslOnConnect` and `SecureSocketOptions.StartTlsWhenAvailable`.  Would it be acceptable if I were to change the instance of `SecureSocketOptions.Auto` in my PR to `SecureSocketOptions.SslOnConnect` which would match the existing code's behavior when `useSsl` is true?

2024-07-02 19:07 UTC, oddstr13 commented
Not ideal, as STARTTLS is often used, but better than what is implemented in this PR right now.

For comparison, Thunderbird gives the following options;
  - None
  - STARTTLS
  - SSL/TLS

3/4 of my currently configured emails are using STARTTLS, the last one SSL (Just providing this as additional context – I have no idea if the last three also supports plain SSL, and I don't feel like fiddling with it right now).

I still maintain that the linked issues are configuration errors (ease of using encryption is getting better (see letsencrypt), but it can still be complicated to set up properly, unfortunately).

The issue seems to be that the certificate are specifying a different dns name than is used to connect to the server (direct IP), so simply connecting to the correct hostname *should* fix it, assuning certificates are otherwise properly configured.

That being said, the current behavior *is* unexpected, as the «Use SSL» checkbox is unckecked, but the user is still getting encryption errors in the logs.

2024-07-02 20:05 UTC, RyanMelena commented
I have modified the PR such that when `useSsl` is enabled, the MailKit connection is created with `SecureSocketOptions.SslOnConnect`, which should be the same behavior as the code exhibited before the PR.

While I agree the ideal situation would be to always use encryption, I can understand why those using a local relay (perhaps with internal dns names) may not care to do so.  I'm hoping that this change should allow those users to utilize webhooks with `Use SSL` disabled without the unexpected encryption errors.  I hope you will agree that this is an improvement to the existing behavior even if not an ideal final implementation.

Perhaps a "feature request" issue to modify the SMTP configuration to support all `MailKit SecureSocketOptions` could be created to capture the details of a further improvement?

2024-07-03 04:16 UTC, oddstr13 commented
> Perhaps a "feature request" issue to modify the SMTP configuration to support all `MailKit SecureSocketOptions` could be created to capture the details of a further improvement?

Had one typed out, but forgot to hit the post button :sweat_smile:

2024-07-03 04:19 UTC, oddstr13 approved these changes
Not ideal, as it excludes STARTTLS, but now it will at least do what it says on the tin.

Beware that this may break existing setups, if the option was disabled, but server enforces STARTTLS.

2024-07-03 12:38 UTC, merged